"""给用户角色增加设置字段

Revision ID: 649bac52ccc1
Revises: 
Create Date: 2021-11-05 16:44:25.779403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '649bac52ccc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_verification_id', table_name='phone_verification')
    op.drop_table('phone_verification')
    op.drop_index('ix_email_verification_id', table_name='email_verification')
    op.drop_table('email_verification')
    op.add_column('role', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'settings')
    op.create_table('email_verification',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('json_remarks', mysql.JSON(), nullable=True),
    sa.Column('create_time', mysql.FLOAT(), nullable=True),
    sa.Column('modify_time', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('use', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_email_verification_id', 'email_verification', ['id'], unique=False)
    op.create_table('phone_verification',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('json_remarks', mysql.JSON(), nullable=True),
    sa.Column('create_time', mysql.FLOAT(), nullable=True),
    sa.Column('modify_time', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('use', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_phone_verification_id', 'phone_verification', ['id'], unique=False)
    # ### end Alembic commands ###
